before:
  hooks:
    - go mod download
builds:
- id: "mdp"
  binary: mdp
  env:
  - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - arm
    - arm64
  goarm:
    - 6
    - 7
archives:
- replacements:
    linux: Linux
    amd64: x86_64
    darwin: macOS
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
